### ISSUE TITLE
Parametre get null and empty list

### ISSUE THREAD

**Issue by darixsamani** [eslamfaisal/FlutterCellInfo#12]
when i try to get cellular network settings it always returns null and empty list.

this is example of CellResponse

{"cellDataList":[],"createdAt":1650498762471,"neighboringCellList":[],"primaryCellList":[]}

**Comment by darixsamani** [comment]
@eslamfaisal i need more information about this issue.

**Comment by Bekeys** [comment]
@eslamfaisal I have the same problem

**Comment by Bekeys** [comment]
I can read data on 4g signal, but not on 5g

**Comment by darixsamani** [comment]
and on 3G signal ?

**Comment by Bekeys** [comment]
Yes, 3g signal also works

**Comment by darixsamani** [comment]
please you can share your code with me ?

**Comment by Bekeys** [comment]
I think it's possible that you don't have location permissions turned on

**Comment by darixsamani** [comment]
please how to request permission for READ_PHONE_STATE ?

**Comment by darixsamani** [comment]
@Bekeys  Please how did you activate it?

**Comment by darixsamani** [comment]
@Bekeys latitude and longitude Cell get null

you can see example below

[{latitude: null, longitude: null, type: WCDMA, dbm: -99}]}

is it same for you ?
